### ISSUE TITLE
If %doc is missing error is thrown

### ISSUE THREAD

**Issue by illuusio** [marguerite/rubygem-rpmspec#2]
If I understand code correctly if %doc is missing this error is thrown
```
+ umask 022
+ cd /home/user/rpmbuild/BUILD
+ node2rpm-server --prep
/usr/lib64/ruby/gems/2.4.0/gems/rpmspec-1.0.0/lib/rpmspec/filelist.rb:42:in `block (2 levels) in files': undefined local variable or method `types' for #<RPMSpec::Filelist:0x0000000001178440> (NameError)
Did you mean?  type
        from /usr/lib64/ruby/gems/2.4.0/gems/rpmspec-1.0.0/lib/rpmspec/filelist.rb:41:in `each'
        from /usr/lib64/ruby/gems/2.4.0/gems/rpmspec-1.0.0/lib/rpmspec/filelist.rb:41:in `block in files'
        from /usr/lib64/ruby/gems/2.4.0/gems/rpmspec-1.0.0/lib/rpmspec/filelist.rb:37:in `each'
        from /usr/lib64/ruby/gems/2.4.0/gems/rpmspec-1.0.0/lib/rpmspec/filelist.rb:37:in `files'
        from /usr/lib64/ruby/gems/2.4.0/gems/rpmspec-1.0.0/lib/rpmspec/parser.rb:27:in `parse'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/system.rb:32:in `buildroot'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/system.rb:27:in `buildroot'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:10:in `initialize'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/bin/node2rpm-server:7:in `new'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/bin/node2rpm-server:7:in `<top (required)>'
        from /usr/bin/node2rpm-server:23:in `load'
        from /usr/bin/node2rpm-server:23:in `<main>'
virhe: Bad exit status from /var/tmp/rpm-tmp.N4LGNG (%prep)
```

**Comment by marguerite** [comment]
@illuusio nope. 'types' was a typo for 'files'.
